use std::io::Write;
use std::process::Command;

fn main() {
    let mut build_info = std::fs::File::create("./src/build_info.rs").unwrap();
    let git_command = "git rev-parse HEAD";
    let res = Command::new("sh")
        .arg("-c")
        .arg(git_command)
        .output()
        .unwrap();
    let git_hash = String::from_utf8(res.stdout).unwrap().trim().to_string();
    let git_hash_8 = &git_hash[0..8];
    let content = format!(
        r#"
    #![allow(dead_code)]
    // This file is auto generated by build.rs 
    pub const GIT_HASH:&str = "{}";
    pub const GIT_HASH_8:&str = "{}";
    "#,
        git_hash, git_hash_8
    );
    build_info.write_all(content.as_bytes()).unwrap();
}
