[package]
name = "shuba"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.1", features = ["io-util", "rt", "macros"] }
derive_builder = "0.20.0"
#thirtyfour = { version = "0.33.0" }
futures = "0.3.30"
clap = "4.5.11"
indicatif = { version = "0.17.8" }
fantoccini = "0.21.0"
serde = "1.0.204"
serde_json = "1.0.122"
[profile.release]
lto = true
codegen-units = 1
#panic = 'abort'

[features]
shuba = []
full = ["shuba"]

